---
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# Env variable ANSIBLE_LIBRARY in to workaround issue ansible/ansible-lint#644
lint: |
  set -e
  yamllint .
  ANSIBLE_LIBRARY=${MOLECULE_EPHEMERAL_DIRECTORY}/roles/informatiquecdc.win_pending_reboot/library/\
  :${MOLECULE_EPHEMERAL_DIRECTORY}/library/:${MOLECULE_PROJECT_DIRECTORY}/library/ ansible-lint
platforms:
  - name: vagrant-win${WIN_VERSION:-2012R2}
    box: jpmat/WindowsServer${WIN_VERSION:-2012R2}
    memory: 4096
    instance_raw_config_args:
      - "vm.boot_timeout = 1200"
provisioner:
  name: ansible
  inventory:
    host_vars:
      vagrant-win${WIN_VERSION:-2012R2}:
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55986
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: https
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 200
        ansible_winrm_read_timeout_sec: 300
verifier:
  name: ansible
